name: build

on: 
  workflow_call:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x]
        os: [ubuntu-latest, windows-latest]

    name: Test on node ${{matrix.node-version}} and ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: npm ci
      run: npm ci