name: npm-publish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: 
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build"
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - run: npm ci
      - name: "Publish on npmjs"
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: "Publish on Github Packages"
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hrax'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}